In [ ]:
import pandas as pd
import numpy as np

import jsonsteam_game_appid

In [33]:
steam_game_appid = json.load(open('./steam_data_sci/steam_appid.json'))
steam_game_appid = steam_game_appid['applist']['apps']

          appid                                    name
9        216938           Pieterw test app76 ( 216938 )
10       660010                                   test2
11       660130                                   test3
32      1826300  SOTANO - Mystery Escape Room Adventure
33      1826310                     Porcelain Mask Demo
...         ...                                     ...
154793   258550                   Rust Dedicated Server
154794  1502190                              From Space
154795  1470390                           City of Beats
154796  1460790                     Bartender Simulator
154797  1948800      Yi Xian: The Cultivation Card Game

[154769 rows x 2 columns]

# Clean data

In [38]:
appid_df = pd.DataFrame(steam_game_appid)
appid_df = appid_df[appid_df['name'].str.len() > 0]
appid_df

          appid                                    name
9        216938           Pieterw test app76 ( 216938 )
10       660010                                   test2
11       660130                                   test3
32      1826300  SOTANO - Mystery Escape Room Adventure
33      1826310                     Porcelain Mask Demo
...         ...                                     ...
154793   258550                   Rust Dedicated Server
154794  1502190                              From Space
154795  1470390                           City of Beats
154796  1460790                     Bartender Simulator
154797  1948800      Yi Xian: The Cultivation Card Game

[154769 rows x 2 columns]